const CONSTANTS: {
  SUCCESS_MARKER_DURATION: number,
  TOTAL_QUESTIONS: number,
  INITIAL_SCORE: number,
  REDUCE_SCORE_BY: number,
  REDUCE_INTERVAL: number,
  TOTAL_INTERVALS: Function
} = {
  SUCCESS_MARKER_DURATION: parseInt(process.env.NEXT_PUBLIC_DURATION_SUCCESS_INDICATOR),
  TOTAL_QUESTIONS: parseInt(process.env.NEXT_PUBLIC_TOTAL_QUESTIONS),
  INITIAL_SCORE: parseInt(process.env.NEXT_PUBLIC_INITIAL_SCORE),
  REDUCE_SCORE_BY: parseInt(process.env.NEXT_PUBLIC_REDUCE_SCORE_BY),
  REDUCE_INTERVAL: parseInt(process.env.NEXT_PUBLIC_REDUCE_SCORE_INTERVAL),
  TOTAL_INTERVALS: function(): number {
    return CONSTANTS['INITIAL_SCORE'] / CONSTANTS['REDUCE_SCORE_BY'];
  }
};

export default CONSTANTS;
